In [1]:
import numpy as np

In [8]:
num1 = np.arange(1, 17)
print(num1)

num1 = num1.reshape(4, 4) 
print(num1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
num2 = np.arange(10, 51 ,5)
print(num2)

num2 = np.arange(10, 50 ,5)

num2 = num2.reshape(2, 4)
print(num2)

[10 15 20 25 30 35 40 45 50]
[[10 15 20 25]
 [30 35 40 45]]


In [18]:
num3 = np.random.randint(1, 101, (3, 3))  
print(num3)

print()

print('max :', num3.max())  
print('min :', num3.min()) 

[[45 17 34]
 [26 72 68]
 [60  4 49]]

max : 72
min : 4


In [26]:
num4 = np.random.choice(np.arange(0, 21), 10, replace=False)
print(num4)

print(num4[0:5])
print(num4[::2])
print(num4[::-1])

[15 11 13  9  8 17 18 20 14 12]
[15 11 13  9  8]
[15 13  8 18 14]
[12 14 20 18 17  8  9 13 11 15]


In [29]:
num5 = np.random.choice(np.arange(1, 51), 20, replace=False)
print(num5)

num5 = num5.reshape(4, 5)
print(num5)
print(num5[2][4])

[23  5 42 33  1 49 31 21 10 30 27  3 45 29 26 16 22  4 28 39]
[[23  5 42 33  1]
 [49 31 21 10 30]
 [27  3 45 29 26]
 [16 22  4 28 39]]
26


In [32]:
num6 = np.random.choice(np.arange(0, 101), 15, replace=False)
print(num6)

print(np.argmax(num6))
print(np.argmin(num6))

[54 86 78 15 70 16 51 48 92  3 50 33 23 40 10]
8
9


In [ ]:
## המשך לשאלה 6 לא הצלחתי 